# Here we are using the local image called run:v1 as our base image in FROM
FROM run:v1
#Using the old image called run:v1 for building this
CMD ["nginx","-g","daemon off;"]
#Here we are running the nginx in foreground