# This FROM pulls the image from the docker hub
FROM almalinux:9

# This RUN command is used to install packages, dependencies and other utilities into the image
RUN dnf install nginx -y        #This command will install the nginx webserver into the image
